// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ShortUrl  string
	LongUrl   string
	CreatedAt pgtype.Timestamp
}
