// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package repository

import (
	"context"
)

const createShortURL = `-- name: CreateShortURL :exec
INSERT INTO urls (short_url, long_url) VALUES ($1, $2)
`

type CreateShortURLParams struct {
	ShortUrl string
	LongUrl  string
}

func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) error {
	_, err := q.db.Exec(ctx, createShortURL, arg.ShortUrl, arg.LongUrl)
	return err
}

const deleteShortURL = `-- name: DeleteShortURL :exec
DELETE FROM urls WHERE short_url = $1
`

func (q *Queries) DeleteShortURL(ctx context.Context, shortUrl string) error {
	_, err := q.db.Exec(ctx, deleteShortURL, shortUrl)
	return err
}

const getLongURL = `-- name: GetLongURL :one
SELECT long_url FROM urls WHERE short_url = $1
`

func (q *Queries) GetLongURL(ctx context.Context, shortUrl string) (string, error) {
	row := q.db.QueryRow(ctx, getLongURL, shortUrl)
	var long_url string
	err := row.Scan(&long_url)
	return long_url, err
}
