// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: id_generator_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIDRequest) Reset() {
	*x = GenerateIDRequest{}
	mi := &file_id_generator_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIDRequest) ProtoMessage() {}

func (x *GenerateIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_id_generator_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIDRequest.ProtoReflect.Descriptor instead.
func (*GenerateIDRequest) Descriptor() ([]byte, []int) {
	return file_id_generator_service_proto_rawDescGZIP(), []int{0}
}

type GenerateIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RandomID      int64                  `protobuf:"varint,1,opt,name=RandomID,proto3" json:"RandomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIDResponse) Reset() {
	*x = GenerateIDResponse{}
	mi := &file_id_generator_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIDResponse) ProtoMessage() {}

func (x *GenerateIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_id_generator_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIDResponse.ProtoReflect.Descriptor instead.
func (*GenerateIDResponse) Descriptor() ([]byte, []int) {
	return file_id_generator_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIDResponse) GetRandomID() int64 {
	if x != nil {
		return x.RandomID
	}
	return 0
}

var File_id_generator_service_proto protoreflect.FileDescriptor

var file_id_generator_service_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x69, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70,
	0x69, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x44, 0x32, 0x53, 0x0a, 0x12, 0x49, 0x44, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d,
	0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x44, 0x12, 0x16, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x69, 0x73,
	0x50, 0x65, 0x79, 0x6d, 0x61, 0x6e, 0x2f, 0x67, 0x6f, 0x2d, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_id_generator_service_proto_rawDescOnce sync.Once
	file_id_generator_service_proto_rawDescData []byte
)

func file_id_generator_service_proto_rawDescGZIP() []byte {
	file_id_generator_service_proto_rawDescOnce.Do(func() {
		file_id_generator_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_id_generator_service_proto_rawDesc), len(file_id_generator_service_proto_rawDesc)))
	})
	return file_id_generator_service_proto_rawDescData
}

var file_id_generator_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_id_generator_service_proto_goTypes = []any{
	(*GenerateIDRequest)(nil),  // 0: api.GenerateIDRequest
	(*GenerateIDResponse)(nil), // 1: api.GenerateIDResponse
}
var file_id_generator_service_proto_depIdxs = []int32{
	0, // 0: api.IDGeneratorService.GenerateID:input_type -> api.GenerateIDRequest
	1, // 1: api.IDGeneratorService.GenerateID:output_type -> api.GenerateIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_id_generator_service_proto_init() }
func file_id_generator_service_proto_init() {
	if File_id_generator_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_id_generator_service_proto_rawDesc), len(file_id_generator_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_id_generator_service_proto_goTypes,
		DependencyIndexes: file_id_generator_service_proto_depIdxs,
		MessageInfos:      file_id_generator_service_proto_msgTypes,
	}.Build()
	File_id_generator_service_proto = out.File
	file_id_generator_service_proto_goTypes = nil
	file_id_generator_service_proto_depIdxs = nil
}
